// Code generated by protoc-gen-go. DO NOT EDIT.
// source: likes.proto

package likes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	post "github.com/wrrn/natter/pkg/post"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateLikesRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLikesRequest) Reset()         { *m = UpdateLikesRequest{} }
func (m *UpdateLikesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLikesRequest) ProtoMessage()    {}
func (*UpdateLikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cff81f36f81c8d8e, []int{0}
}

func (m *UpdateLikesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLikesRequest.Unmarshal(m, b)
}
func (m *UpdateLikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLikesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLikesRequest.Merge(m, src)
}
func (m *UpdateLikesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLikesRequest.Size(m)
}
func (m *UpdateLikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLikesRequest proto.InternalMessageInfo

func (m *UpdateLikesRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateLikesRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UpdateLikesResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TotalLikes           int64    `protobuf:"varint,2,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLikesResponse) Reset()         { *m = UpdateLikesResponse{} }
func (m *UpdateLikesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLikesResponse) ProtoMessage()    {}
func (*UpdateLikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cff81f36f81c8d8e, []int{1}
}

func (m *UpdateLikesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLikesResponse.Unmarshal(m, b)
}
func (m *UpdateLikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLikesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLikesResponse.Merge(m, src)
}
func (m *UpdateLikesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLikesResponse.Size(m)
}
func (m *UpdateLikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLikesResponse proto.InternalMessageInfo

func (m *UpdateLikesResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateLikesResponse) GetTotalLikes() int64 {
	if m != nil {
		return m.TotalLikes
	}
	return 0
}

type GetTrendingRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTrendingRequest) Reset()         { *m = GetTrendingRequest{} }
func (m *GetTrendingRequest) String() string { return proto.CompactTextString(m) }
func (*GetTrendingRequest) ProtoMessage()    {}
func (*GetTrendingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cff81f36f81c8d8e, []int{2}
}

func (m *GetTrendingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrendingRequest.Unmarshal(m, b)
}
func (m *GetTrendingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrendingRequest.Marshal(b, m, deterministic)
}
func (m *GetTrendingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrendingRequest.Merge(m, src)
}
func (m *GetTrendingRequest) XXX_Size() int {
	return xxx_messageInfo_GetTrendingRequest.Size(m)
}
func (m *GetTrendingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrendingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrendingRequest proto.InternalMessageInfo

func (m *GetTrendingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetTrendingResponse struct {
	Posts                []*TrendingPost `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTrendingResponse) Reset()         { *m = GetTrendingResponse{} }
func (m *GetTrendingResponse) String() string { return proto.CompactTextString(m) }
func (*GetTrendingResponse) ProtoMessage()    {}
func (*GetTrendingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cff81f36f81c8d8e, []int{3}
}

func (m *GetTrendingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrendingResponse.Unmarshal(m, b)
}
func (m *GetTrendingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrendingResponse.Marshal(b, m, deterministic)
}
func (m *GetTrendingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrendingResponse.Merge(m, src)
}
func (m *GetTrendingResponse) XXX_Size() int {
	return xxx_messageInfo_GetTrendingResponse.Size(m)
}
func (m *GetTrendingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrendingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrendingResponse proto.InternalMessageInfo

func (m *GetTrendingResponse) GetPosts() []*TrendingPost {
	if m != nil {
		return m.Posts
	}
	return nil
}

type TrendingPost struct {
	Post                 *post.Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	NumLikes             int64      `protobuf:"varint,2,opt,name=num_likes,json=numLikes,proto3" json:"num_likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrendingPost) Reset()         { *m = TrendingPost{} }
func (m *TrendingPost) String() string { return proto.CompactTextString(m) }
func (*TrendingPost) ProtoMessage()    {}
func (*TrendingPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_cff81f36f81c8d8e, []int{4}
}

func (m *TrendingPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrendingPost.Unmarshal(m, b)
}
func (m *TrendingPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrendingPost.Marshal(b, m, deterministic)
}
func (m *TrendingPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrendingPost.Merge(m, src)
}
func (m *TrendingPost) XXX_Size() int {
	return xxx_messageInfo_TrendingPost.Size(m)
}
func (m *TrendingPost) XXX_DiscardUnknown() {
	xxx_messageInfo_TrendingPost.DiscardUnknown(m)
}

var xxx_messageInfo_TrendingPost proto.InternalMessageInfo

func (m *TrendingPost) GetPost() *post.Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *TrendingPost) GetNumLikes() int64 {
	if m != nil {
		return m.NumLikes
	}
	return 0
}

func init() {
	proto.RegisterType((*UpdateLikesRequest)(nil), "tutorial.likes.UpdateLikesRequest")
	proto.RegisterType((*UpdateLikesResponse)(nil), "tutorial.likes.UpdateLikesResponse")
	proto.RegisterType((*GetTrendingRequest)(nil), "tutorial.likes.GetTrendingRequest")
	proto.RegisterType((*GetTrendingResponse)(nil), "tutorial.likes.GetTrendingResponse")
	proto.RegisterType((*TrendingPost)(nil), "tutorial.likes.TrendingPost")
}

func init() { proto.RegisterFile("likes.proto", fileDescriptor_cff81f36f81c8d8e) }

var fileDescriptor_cff81f36f81c8d8e = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xc1, 0x4f, 0xea, 0x40,
	0x10, 0xc6, 0x29, 0xd0, 0x97, 0xc7, 0x94, 0x70, 0x58, 0x38, 0x10, 0xde, 0x4b, 0x6c, 0xd6, 0x83,
	0xc4, 0x43, 0x6b, 0xea, 0xdd, 0x83, 0x17, 0xa3, 0xf1, 0x60, 0x0a, 0x26, 0xc6, 0xc4, 0x98, 0x02,
	0x1b, 0xdc, 0xd0, 0xee, 0xd6, 0xed, 0xac, 0xfe, 0x3d, 0xfe, 0xa7, 0xa6, 0x53, 0x88, 0xd4, 0x12,
	0x6f, 0xde, 0x76, 0x67, 0xe6, 0xfb, 0xed, 0x7c, 0x5f, 0x0b, 0x5e, 0x2a, 0x37, 0xa2, 0x08, 0x72,
	0xa3, 0x51, 0xb3, 0x01, 0x5a, 0xd4, 0x46, 0x26, 0x69, 0x40, 0xd5, 0x09, 0xe4, 0xba, 0xc0, 0xaa,
	0xc7, 0x2f, 0x80, 0xdd, 0xe7, 0xab, 0x04, 0xc5, 0x6d, 0xd9, 0x8a, 0xc5, 0xab, 0x15, 0x05, 0x32,
	0x06, 0x5d, 0x6b, 0xe5, 0x6a, 0xec, 0xf8, 0xce, 0xb4, 0x17, 0xd3, 0x99, 0x8d, 0xc0, 0x5d, 0x6a,
	0xab, 0x70, 0xdc, 0xf6, 0x9d, 0x69, 0x27, 0xae, 0x2e, 0xfc, 0x06, 0x86, 0x35, 0x7d, 0x91, 0x6b,
	0x55, 0x88, 0x83, 0x80, 0x23, 0xf0, 0x50, 0x63, 0x92, 0x3e, 0xd3, 0x16, 0x5b, 0x0c, 0x50, 0x89,
	0xc4, 0xfc, 0x14, 0xd8, 0x95, 0xc0, 0xb9, 0x11, 0x6a, 0x25, 0xd5, 0x7a, 0xb7, 0xcb, 0x08, 0xdc,
	0x54, 0x66, 0x12, 0x89, 0xe5, 0xc6, 0xd5, 0x85, 0x5f, 0xc3, 0xb0, 0x36, 0xbb, 0x7d, 0x37, 0x02,
	0xb7, 0x34, 0x57, 0x8c, 0x1d, 0xbf, 0x33, 0xf5, 0xa2, 0xff, 0x41, 0xdd, 0x7a, 0xb0, 0x13, 0xdc,
	0xe9, 0x02, 0xe3, 0x6a, 0x94, 0xcf, 0xa1, 0xbf, 0x5f, 0x66, 0x27, 0xd0, 0x2d, 0x1b, 0xf4, 0x9e,
	0x17, 0x0d, 0xbf, 0x10, 0x14, 0x1b, 0x29, 0x69, 0x80, 0xfd, 0x83, 0x9e, 0xb2, 0x59, 0xcd, 0xce,
	0x5f, 0x65, 0x33, 0x32, 0x13, 0x7d, 0xb4, 0xa1, 0x4f, 0xa7, 0x99, 0x30, 0x6f, 0x72, 0x29, 0xd8,
	0x03, 0x78, 0x7b, 0x49, 0x31, 0xfe, 0x7d, 0xb5, 0xe6, 0x67, 0x98, 0x1c, 0xff, 0x38, 0x53, 0x59,
	0xe6, 0xad, 0x92, 0xbc, 0x97, 0x45, 0x93, 0xdc, 0x0c, 0xb5, 0x49, 0x3e, 0x10, 0x26, 0x6f, 0xb1,
	0x27, 0x18, 0xcc, 0xd0, 0x88, 0x24, 0xfb, 0x05, 0xf8, 0x99, 0x73, 0xc9, 0x1f, 0xfd, 0xb5, 0xc4,
	0x17, 0xbb, 0x08, 0x96, 0x3a, 0x0b, 0xdf, 0x8d, 0x51, 0xa1, 0x4a, 0x10, 0x85, 0x09, 0xf3, 0xcd,
	0x3a, 0x24, 0xed, 0xe2, 0x0f, 0xfd, 0xa7, 0xe7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x45,
	0x12, 0x33, 0xd2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LikesServiceClient is the client API for LikesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LikesServiceClient interface {
	UpdateLikes(ctx context.Context, in *UpdateLikesRequest, opts ...grpc.CallOption) (*UpdateLikesResponse, error)
	GetTrending(ctx context.Context, in *GetTrendingRequest, opts ...grpc.CallOption) (*GetTrendingResponse, error)
	StreamTrending(ctx context.Context, in *GetTrendingRequest, opts ...grpc.CallOption) (LikesService_StreamTrendingClient, error)
}

type likesServiceClient struct {
	cc *grpc.ClientConn
}

func NewLikesServiceClient(cc *grpc.ClientConn) LikesServiceClient {
	return &likesServiceClient{cc}
}

func (c *likesServiceClient) UpdateLikes(ctx context.Context, in *UpdateLikesRequest, opts ...grpc.CallOption) (*UpdateLikesResponse, error) {
	out := new(UpdateLikesResponse)
	err := c.cc.Invoke(ctx, "/tutorial.likes.LikesService/UpdateLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likesServiceClient) GetTrending(ctx context.Context, in *GetTrendingRequest, opts ...grpc.CallOption) (*GetTrendingResponse, error) {
	out := new(GetTrendingResponse)
	err := c.cc.Invoke(ctx, "/tutorial.likes.LikesService/GetTrending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likesServiceClient) StreamTrending(ctx context.Context, in *GetTrendingRequest, opts ...grpc.CallOption) (LikesService_StreamTrendingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LikesService_serviceDesc.Streams[0], "/tutorial.likes.LikesService/StreamTrending", opts...)
	if err != nil {
		return nil, err
	}
	x := &likesServiceStreamTrendingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LikesService_StreamTrendingClient interface {
	Recv() (*GetTrendingResponse, error)
	grpc.ClientStream
}

type likesServiceStreamTrendingClient struct {
	grpc.ClientStream
}

func (x *likesServiceStreamTrendingClient) Recv() (*GetTrendingResponse, error) {
	m := new(GetTrendingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LikesServiceServer is the server API for LikesService service.
type LikesServiceServer interface {
	UpdateLikes(context.Context, *UpdateLikesRequest) (*UpdateLikesResponse, error)
	GetTrending(context.Context, *GetTrendingRequest) (*GetTrendingResponse, error)
	StreamTrending(*GetTrendingRequest, LikesService_StreamTrendingServer) error
}

func RegisterLikesServiceServer(s *grpc.Server, srv LikesServiceServer) {
	s.RegisterService(&_LikesService_serviceDesc, srv)
}

func _LikesService_UpdateLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServiceServer).UpdateLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.likes.LikesService/UpdateLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServiceServer).UpdateLikes(ctx, req.(*UpdateLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikesService_GetTrending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServiceServer).GetTrending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.likes.LikesService/GetTrending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServiceServer).GetTrending(ctx, req.(*GetTrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikesService_StreamTrending_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTrendingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LikesServiceServer).StreamTrending(m, &likesServiceStreamTrendingServer{stream})
}

type LikesService_StreamTrendingServer interface {
	Send(*GetTrendingResponse) error
	grpc.ServerStream
}

type likesServiceStreamTrendingServer struct {
	grpc.ServerStream
}

func (x *likesServiceStreamTrendingServer) Send(m *GetTrendingResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LikesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.likes.LikesService",
	HandlerType: (*LikesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateLikes",
			Handler:    _LikesService_UpdateLikes_Handler,
		},
		{
			MethodName: "GetTrending",
			Handler:    _LikesService_GetTrending_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTrending",
			Handler:       _LikesService_StreamTrending_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "likes.proto",
}
