// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatePostRequest struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CreatePostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type ListPostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(m, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

type ListPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(m, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type BatchGetPostsRequest struct {
	Uuids                []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetPostsRequest) Reset()         { *m = BatchGetPostsRequest{} }
func (m *BatchGetPostsRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetPostsRequest) ProtoMessage()    {}
func (*BatchGetPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *BatchGetPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetPostsRequest.Unmarshal(m, b)
}
func (m *BatchGetPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetPostsRequest.Marshal(b, m, deterministic)
}
func (m *BatchGetPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetPostsRequest.Merge(m, src)
}
func (m *BatchGetPostsRequest) XXX_Size() int {
	return xxx_messageInfo_BatchGetPostsRequest.Size(m)
}
func (m *BatchGetPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetPostsRequest proto.InternalMessageInfo

func (m *BatchGetPostsRequest) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

type BatchGetPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetPostsResponse) Reset()         { *m = BatchGetPostsResponse{} }
func (m *BatchGetPostsResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetPostsResponse) ProtoMessage()    {}
func (*BatchGetPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *BatchGetPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetPostsResponse.Unmarshal(m, b)
}
func (m *BatchGetPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetPostsResponse.Marshal(b, m, deterministic)
}
func (m *BatchGetPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetPostsResponse.Merge(m, src)
}
func (m *BatchGetPostsResponse) XXX_Size() int {
	return xxx_messageInfo_BatchGetPostsResponse.Size(m)
}
func (m *BatchGetPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetPostsResponse proto.InternalMessageInfo

func (m *BatchGetPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Post struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Post) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePostRequest)(nil), "tutorial.post.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "tutorial.post.CreatePostResponse")
	proto.RegisterType((*ListPostsRequest)(nil), "tutorial.post.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "tutorial.post.ListPostsResponse")
	proto.RegisterType((*BatchGetPostsRequest)(nil), "tutorial.post.BatchGetPostsRequest")
	proto.RegisterType((*BatchGetPostsResponse)(nil), "tutorial.post.BatchGetPostsResponse")
	proto.RegisterType((*Post)(nil), "tutorial.post.Post")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x43, 0x4b, 0x4d, 0x98, 0xa6, 0x49, 0x3b, 0xd6, 0x84, 0x70, 0x29, 0x5d, 0x35, 0xd6,
	0xc4, 0x40, 0x52, 0xcf, 0x7a, 0xc0, 0x83, 0x17, 0x63, 0x14, 0x6f, 0xbd, 0x51, 0xdc, 0x50, 0xa2,
	0x65, 0x71, 0x77, 0xd0, 0x97, 0xf0, 0xa1, 0xcd, 0x02, 0xd6, 0x82, 0xb6, 0x07, 0x6f, 0x33, 0x93,
	0x6f, 0xbe, 0x81, 0x1f, 0x00, 0x72, 0xa1, 0xc8, 0xcb, 0xa5, 0x20, 0x81, 0x03, 0x2a, 0x48, 0xc8,
	0x34, 0x7a, 0xf5, 0xf4, 0x90, 0x9d, 0xc2, 0xe8, 0x46, 0xf2, 0x88, 0xf8, 0x83, 0x50, 0x14, 0xf2,
	0xb7, 0x82, 0x2b, 0xc2, 0x21, 0x74, 0xd7, 0x2a, 0xb1, 0x3b, 0xae, 0x31, 0xb3, 0x42, 0x5d, 0xb2,
	0x2b, 0xc0, 0x6d, 0x4c, 0xe5, 0x22, 0x53, 0x1c, 0xcf, 0xc0, 0xd4, 0x12, 0xdb, 0x70, 0x8d, 0x59,
	0x7f, 0x7e, 0xe8, 0x35, 0xd4, 0x5e, 0x89, 0x96, 0x00, 0x43, 0x18, 0xde, 0xa5, 0x8a, 0xf4, 0x44,
	0xd5, 0x47, 0xd8, 0x35, 0x8c, 0xb6, 0x66, 0xb5, 0xf1, 0x1c, 0x7a, 0x7a, 0x41, 0xd9, 0x86, 0xdb,
	0xdd, 0xa5, 0xac, 0x08, 0x76, 0x01, 0xe3, 0x20, 0xa2, 0x78, 0x75, 0xcb, 0x1b, 0x5e, 0x1c, 0x43,
	0xaf, 0x28, 0xd2, 0xe7, 0x4a, 0x61, 0x85, 0x55, 0xc3, 0x02, 0x38, 0x6a, 0xd1, 0xff, 0xb9, 0x68,
	0xea, 0x16, 0x11, 0x4c, 0x2d, 0x2d, 0x5f, 0xdb, 0x0a, 0xcb, 0xfa, 0x3b, 0xb2, 0xee, 0x26, 0xb2,
	0xf9, 0x67, 0x07, 0xfa, 0x1a, 0x7f, 0xe2, 0xf2, 0x3d, 0x8d, 0x39, 0x3e, 0x02, 0xfc, 0x44, 0x88,
	0x6e, 0xeb, 0xce, 0xaf, 0x8f, 0xe0, 0x4c, 0xf7, 0x10, 0xf5, 0xb3, 0xdf, 0x83, 0xb5, 0x89, 0x10,
	0x27, 0x2d, 0xbe, 0x1d, 0xb8, 0xe3, 0xee, 0x06, 0x6a, 0xdf, 0x02, 0x06, 0x8d, 0x90, 0xf0, 0xb8,
	0xb5, 0xf2, 0x57, 0xe0, 0xce, 0xc9, 0x7e, 0xa8, 0x72, 0x07, 0xd3, 0xc5, 0x24, 0x49, 0x69, 0x55,
	0x2c, 0xbd, 0x58, 0xac, 0xfd, 0x0f, 0x29, 0x33, 0x3f, 0x8b, 0x88, 0xb8, 0xf4, 0xf3, 0x97, 0xc4,
	0xd7, 0x8b, 0xcb, 0x83, 0xf2, 0x0f, 0xbd, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xf9, 0xef,
	0x44, 0xaf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	BatchGetPosts(ctx context.Context, in *BatchGetPostsRequest, opts ...grpc.CallOption) (*BatchGetPostsResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/tutorial.post.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/tutorial.post.PostService/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) BatchGetPosts(ctx context.Context, in *BatchGetPostsRequest, opts ...grpc.CallOption) (*BatchGetPostsResponse, error) {
	out := new(BatchGetPostsResponse)
	err := c.cc.Invoke(ctx, "/tutorial.post.PostService/BatchGetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	BatchGetPosts(context.Context, *BatchGetPostsRequest) (*BatchGetPostsResponse, error)
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.post.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.post.PostService/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_BatchGetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).BatchGetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.post.PostService/BatchGetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).BatchGetPosts(ctx, req.(*BatchGetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostService_ListPosts_Handler,
		},
		{
			MethodName: "BatchGetPosts",
			Handler:    _PostService_BatchGetPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
